### ISSUE TITLE
接入更多插件

### ISSUE THREAD

**Issue by zhangruhong** [AliyunCodePipeline/issues#11]
比如checkstyle、findbugs等等

**Comment by ringtail** [comment]
能说下场景和大致的需求吗，因为插件有很多个不同的实现，findbugs也会有不同的版本和实现，想问下具体的需求，我们会尽快提供最恰当的方案，然后和您讨论

**Comment by zhangruhong** [comment]
前面我想的是一般规范点的企业会对代码格式风格/代码潜在问题进行检查 现在突然觉得这种检查放在代码提交的时候比较合适
