### ISSUE TITLE
优化日志

### ISSUE THREAD

**Issue by zuoge85** [AliyunCodePipeline/issues#14]
日志长时间卡在下面过程，直到突然结束才能看见详情

/bin/bash -c "chmod +x /tmp/hudson823654282958931240.sh;chown -R jenkins:jenkins /home/jenkins;su -s /bin/sh -c /tmp/hudson823654282958931240.sh jenkins"

能否去掉大量无意义的下载进度日志

**Comment by ringtail** [comment]
短时间可以通过mvn -B的方式解决

**Comment by ringtail** [comment]
待发布，预计下周一发布

**Comment by ringtail** [comment]
已发布
