### ISSUE TITLE
申请添加sbt支持

### ISSUE THREAD

**Issue by livehl** [AliyunCodePipeline/issues#27]
https://wiki.jenkins.io/display/JENKINS/sbt+plugin

我们现在都是自建的jenkins，从阿里云拉代码，然后推到阿里云容器
要是能直接支持，省好多事情

**Comment by zuoky** [comment]
嗯，我们也确实需要这个功能。

**Comment by ringtail** [comment]
收到，我们检查下插件的代码，进行下安全加固

**Comment by ringtail** [comment]
是否我们在Java环境中支持scalac就可以通过shell满足需求

**Comment by zuoky** [comment]
其实你们可以加载jenkins plugin （sbt）就并配置sbt launcher （0.13.15)。

ringtail <notifications@github.com>于2017年10月20日 周五16:55写道：

**Comment by ringtail** [comment]
SBT的插件我大致看了下，整体的功能比较简单，因为过多的插件会影响Jenkins的性能，所以我们比较倾向在Java环境中支持scala的构建以及sbt工具。目前准备支持的版本如下：
ENV SCALA_VERSION 2.12.3
ENV SBT_VERSION 1.0.2
是否能够满足您的需求

**Comment by livehl** [comment]
只要有任意一个能用的sbt，项目使用的版本它会自己下载,scala版本也是

**Comment by livehl** [comment]
另外，0.13.x 和1.x似乎不兼容。等我查查看
结论: 不存在这个问题，可以使用1.0.2的版本

**Comment by livehl** [comment]
实际上只需要 sbt即可，scala环境不是必须的，JDK环境是必须的。
sbt构建过程中，会下载大量的依赖库(包括scala-library,scala-compile,以及sbt自身不同的版本)，保存这些依赖库能极大加速构建过程。

**Comment by ringtail** [comment]
理解了，我们尝试测试下。

**Comment by qinyujia** [comment]
@livehl 目前环境已经安装1.0.2版本的sbt，由于要下载依赖，建议使用海外Java构建环境。

**Comment by livehl** [comment]
有一个小问题希望修复下。执行命令的时候，看不到具体的内容，需要等待执行结果才能看到。
First time build. Skipping changelog.[YAD-PLUGIN] Injecting DOCKER_CONTAINER_ID variable.[YAD-PLUGIN] Injecting JENKINS_CLOUD_ID variable.[YAD-PLUGIN] DOCKER_HOST variable.[vega] $ /bin/bash -c "chmod +x /tmp/hudson2337855463769671073.sh;chown -R jenkins:jenkins /home/jenkins;su -s /bin/sh -c /tmp/hudson2337855463769671073.sh jenkins"

**Comment by ringtail** [comment]
这个地方是这样的，日志是有缓冲的，如果没有写满缓冲区目前是不会显示，放置每条日志并发写带来的性能问题。
