### ISSUE TITLE
部署环境AliyunLinux的支持

### ISSUE THREAD

**Issue by ringtail** [AliyunCodePipeline/issues#5]
支持版本需补充

**Comment by liupengjava** [comment]
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	AlibabaCloudEnterpriseServer
Description:	Alibaba Cloud Enterprise Linux Server release 17.01.2 (Golden Toad)
Release:	17.01.2
Codename:	GoldenToad

Linux prod1 4.4.24-2.al7.x86_64 #1 SMP Wed Jan 4 17:23:01 CST 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by zhuzhih2017** [comment]
Plan to support it at next weekend.

**Comment by ringtail** [comment]
已发布
